<?php
/**
 * Plugin Name:       Advanced Custom Fields: Icomoon
 * Plugin URI:        https://wordpress.org/plugins/acf-icomoon/
 * Description:       🔩 Add a field to select icons from a selection.json file generated by IcoMoon
 * Version:           3.1
 * Requires at least: 5.2
 * Requires PHP:      7.2
 * Author:            ViiVue
 * Author URI:        https://www.viivue.com/
 * Text Domain:       acf-icomoon
 */

// exit if accessed directly
if(!defined('ABSPATH')){
	exit;
}


// check if class already exists
if(!class_exists('dh_acf_icomoon')){
	
	class dh_acf_icomoon{
		function __construct(){
			
			// vars
			$this->settings = array(
				'version' => '3.1',
				'url'     => plugin_dir_url(__FILE__),
				'path'    => plugin_dir_path(__FILE__)
			);
			
			
			// set text domain
			load_plugin_textdomain('dh_acf_icomoon', false, plugin_basename(dirname(__FILE__)) . '/lang');
			
			
			// include field
			add_action('acf/include_field_types', array($this, 'include_field_types')); // v5
		}
		
		
		/*
		*  This function will include the field type class
		*  @param	$version (int) major ACF version. Defaults to false
		*  @return	n/a
		*/
		
		function include_field_types($version = false){
			
			// include
			include_once('inc/fields.php');
			
		}
		
	}
	
	// initialize
	new dh_acf_icomoon();
}