<?php
/*
Plugin Name: Advanced Custom Fields: Icomoon
Plugin URI:
Description: Add a field to select icons from a selection.json file generated by IcoMoon
Version: 3.1
Author: Dustin Henderson
Author URI:
License: GPLv2 or later
License URI: http://www.gnu.org/licenses/gpl-2.0.html
*/

// exit if accessed directly
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}


// check if class already exists
if ( ! class_exists( 'dh_acf_icomoon' ) ) {

	class dh_acf_icomoon {

		/*
		*  __construct
		*
		*  This function will setup the class functionality
		*
		*  @type	function
		*  @date	17/02/2016
		*  @since	1.0.0
		*
		*  @param	n/a
		*  @return	n/a
		*/

		function __construct()
        {

            // vars
            $this->settings = array(
                'version' => '3.1',
                'url' => plugin_dir_url(__FILE__),
                'path' => plugin_dir_path(__FILE__)
            );


            // set text domain
            // https://codex.wordpress.org/Function_Reference/load_plugin_textdomain
            load_plugin_textdomain('dh_acf_icomoon', false, plugin_basename(dirname(__FILE__)) . '/lang');


            // include field
            add_action('acf/include_field_types', array($this, 'include_field_types')); // v5
        }


		/*
		*  include_field_types
		*
		*  This function will include the field type class
		*
		*  @type	function
		*  @date	17/02/2016
		*  @since	1.0.0
		*
		*  @param	$version (int) major ACF version. Defaults to false
		*  @return	n/a
		*/

		function include_field_types( $version = false ) {

			// include
			include_once( 'inc/fields.php' );

		}

	}

	// initialize
	new dh_acf_icomoon();
}